# ２章　小売店のデータでデータ加工を行う１０本ノック

本章では、ある小売店の売上履歴と顧客台帳データを用いて、データ分析の素地となる「データの加工」を習得することが目的です。
実際の現場データは手入力のExcel等、決して綺麗なデータではない事が多いため、
データの揺れや整合性の担保など、汚いデータを取り扱うデータ加工を主体に進めて行きます。

### ノック１１：データを読み込んでみよう

In [1]:
import pandas as pd
uriage_data = pd.read_csv("uriage.csv")
uriage_data.head()

         purchase_date item_name  item_price customer_name
0  2019-06-13 18:02:34       商品A       100.0         深井菜々美
1  2019-07-13 13:05:29     商 品 S         NaN          浅田賢二
2  2019-05-11 19:42:07     商 品 a         NaN          南部慶二
3  2019-02-12 23:40:45       商品Z      2600.0          麻生莉緒
4  2019-04-22 03:09:35       商品a         NaN          平田鉄二

In [2]:
kokyaku_data = pd.read_excel("kokyaku_daicho.xlsx")
kokyaku_data.head()

      顧客名        かな  地域                     メールアドレス         登録日
0   須賀ひとみ    すが ひとみ  H市     suga_hitomi@example.com  2018/01/04
1  岡田　 敏也   おかだ としや  E市   okada_toshiya@example.com       42782
2    芳賀 希    はが のぞみ  A市     haga_nozomi@example.com  2018/01/07
3   荻野  愛    おぎの あい  F市        ogino_ai@example.com       42872
4   栗田 憲一  くりた けんいち  E市  kurita_kenichi@example.com       43127

### ノック１２：データの揺れを見てみよう

In [3]:
uriage_data["item_name"].head()

0      商品A
1    商 品 S
2    商 品 a
3      商品Z
4      商品a
Name: item_name, dtype: object

In [4]:
uriage_data["item_price"].head()

0     100.0
1       NaN
2       NaN
3    2600.0
4       NaN
Name: item_price, dtype: float64

In [5]:
kokyaku_data["登録日"].head()

0    2018/01/04
1         42782
2    2018/01/07
3         42872
4         43127
Name: 登録日, dtype: object

### ノック１３：データに揺れがあるまま集計しよう

In [6]:
uriage_data["purchase_date"] = pd.to_datetime(uriage_data["purchase_date"])
uriage_data["purchase_month"] = uriage_data["purchase_date"].dt.strftime("%Y%m")
res = uriage_data.pivot_table(index="purchase_month", columns="item_name", aggfunc="size", fill_value=0)
res

item_name,商品W,商 品 n,商品E,商品M,商品P,商品S,商品W,商品X,商 品O,商 品Q,...,商品k,商品l,商品o,商品p,商品r,商品s,商品t,商品v,商品x,商品y
purchase_month,,,,,,,,,,,,,,,,,,,,,
201901,0,1,0,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0
201902,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,1,1,0,0
201903,0,0,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
201904,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
201905,0,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
201906,0,0,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,1,0
201907,0,0,0,0,0,0,0,0,1,0,...,0,0,1,0,2,0,0,0,0,0

In [7]:
res = uriage_data.pivot_table(index="purchase_month", columns="item_name", values="item_price", aggfunc="sum", fill_value=0)
res

item_name,商品W,商 品 n,商品E,商品M,商品P,商品S,商品W,商品X,商 品O,商 品Q,...,商品k,商品l,商品o,商品p,商品r,商品s,商品t,商品v,商品x,商品y
purchase_month,,,,,,,,,,,,,,,,,,,,,
201901,0,1400,0,0,0,0,0,0,0,0,...,1100,1200,1500,0,0,0,0,0,0,0
201902,0,0,0,0,0,0,0,2400,0,0,...,0,0,0,0,0,1900,2000,2200,0,0
201903,0,0,500,1300,1600,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
201904,2300,0,0,0,0,0,0,0,0,1700,...,0,0,0,0,0,1900,0,0,0,0
201905,0,0,0,0,0,1900,0,0,0,0,...,0,1200,0,0,0,0,0,0,0,2500
201906,0,0,0,0,0,0,2300,0,0,0,...,0,0,0,1600,0,0,0,0,2400,0
201907,0,0,0,0,0,0,0,0,0,0,...,0,0,1500,0,1800,0,0,0,0,0

### ノック１４：商品名の揺れを補正しよう

In [8]:
print(len(pd.unique(uriage_data["item_name"])))

99

In [9]:
uriage_data["item_name"] = uriage_data["item_name"].str.upper()
uriage_data["item_name"] = uriage_data["item_name"].str.replace("　", "")
uriage_data["item_name"] = uriage_data["item_name"].str.replace(" ", "")
uriage_data.sort_values(by=["item_name"], ascending=True)

           purchase_date item_name  item_price customer_name purchase_month
0    2019-06-13 18:02:34       商品A       100.0         深井菜々美         201906
1748 2019-05-19 20:22:22       商品A       100.0          松川綾女         201905
223  2019-06-25 08:13:20       商品A       100.0           板橋隆         201906
1742 2019-06-13 16:03:17       商品A       100.0          小平陽子         201906
1738 2019-02-10 00:28:43       商品A       100.0          松田浩正         201902
1721 2019-02-24 19:18:05       商品A       100.0           楠哲平         201902
1708 2019-03-27 17:10:06       商品A       100.0          西脇礼子         201903
1707 2019-03-25 21:42:02       商品A       100.0          浅見広司         201903
234  2019-03-23 09:32:03       商品A       100.0         赤木だん吉         201903
1684 2019-02-17 20:25:57       商品A       100.0          手塚雅之         201902
497  2019-02-11 03:54:57       商品A       100.0           堀江佑         201902
1761 2019-05-04 14:44:55       商品A       100.0          八木雅彦         201905
1658 2019-03-23 20:08:49       商品A       100.0          片瀬長利         201903
1544 2019-01-21 11:49:01       商品A       100.0           藤広之         201901
1513 2019-04-04 18:58:05       商品A       100.0          河村由樹         201904
1500 2019-02-28 17:25:59       商品A       100.0          赤木愛梨         201902
1498 2019-01-19 12:15:21       商品A       100.0            今茜         201901
1481 2019-03-10 03:52:24       商品A       100.0         石川まさみ         201903
1474 2019-04-11 02:22:17       商品A         NaN          堀北雅彦         201904
274  2019-07-27 01:45:18       商品A       100.0          佐藤慶二         201907
1454 2019-01-16 07:35:54       商品A       100.0          平田鉄二         201901
1398 2019-06-13 02:20:26       商品A       100.0          高沢美咲         201906
1394 2019-07-07 21:49:14       商品A         NaN           楠哲平         201907
1576 2019-05-06 02:40:03       商品A       100.0           楠哲平         201905
211  2019-02-12 02:52:39       商品A       100.0          日野夏希         201902
210  2019-07-08 04:17:01       商品A       100.0          平田鉄二         201907
1835 2019-06-20 12:57:54       商品A       100.0          古川信吾         201906
2384 2019-04-27 02:50:16       商品A       100.0            林勇         201904
117  2019-06-14 09:08:17       商品A       100.0         深井菜々美         201906
2352 2019-07-28 07:55:39       商品A       100.0          矢部夏空         201907
...                  ...       ...         ...           ...            ...
214  2019-06-02 01:01:30       商品Y      2500.0           大山咲         201906
707  2019-02-08 19:17:58       商品Y      2500.0          戸塚美幸         201902
2123 2019-06-19 14:40:25       商品Y         NaN          岩沢那奈         201906
2909 2019-04-27 21:33:34       商品Y      2500.0           横田遥         201904
2910 2019-05-16 07:16:37       商品Y      2500.0          松田浩正         201905
702  2019-06-20 19:09:02       商品Y      2500.0          亀井一徳         201906
198  2019-04-13 13:05:25       商品Y      2500.0          杉下悟志         201904
689  2019-05-24 17:03:58       商品Y      2500.0          矢部美幸         201905
1571 2019-05-10 17:54:12       商品Y         NaN          梅津淳子         201905
833  2019-07-29 11:07:10       商品Y      2500.0           大山咲         201907
743  2019-06-09 04:18:56       商品Y      2500.0          福本美幸         201906
26   2019-05-16 04:45:21       商品Y      2500.0          明石家明         201905
2857 2019-06-13 22:19:16       商品Y      2500.0        田辺きみまろ         201906
2446 2019-03-30 18:50:18       商品Y         NaN          梅村秀樹         201903
2679 2019-05-04 13:03:40       商品Y      2500.0          藤木一恵         201905
1882 2019-07-31 16:58:12       商品Y         NaN         五十嵐春樹         201907
805  2019-07-29 07:17:05       商品Y      2500.0          島孝太郎         201907
2452 2019-05-01 17:42:48       商品Y      2500.0          神原美嘉         201905
2889 2019-06-14 10:11:12       商品Y      2500.0          小松季衣         201906
1732 2019-02-20 05:22:25       商品Y         NaN         河内さとみ         201902
2090 2019-06-13 07:18:45       商品Y      2500.0        大城ケンイチ         201906
2100 2019-02-27 01:24:20       商品Y      2500.0          石渡小雁         201902
1878 2019-01-29 13:58:57       商品Y      2500.0         西原未華子         201901
2527 2019-05-17 18:15:27       商品Y      2500.0           松村聡         201905
2526 2019-05-26 10:26:28       商品Y      2500.0           島英嗣         201905
2880 2019-04-22 00:36:52       商品Y         NaN          田辺光洋         201904
2881 2019-04-30 14:21:09       商品Y         NaN          高原充則         201904
1525 2019-01-24 10:27:23       商品Y      2500.0         五十嵐春樹         201901
1361 2019-05-28 13:45:32       商品Y      2500.0         大崎ヒカル         201905
3    2019-02-12 23:40:45       商品Z      2600.0          麻生莉緒         201902

[2999 rows x 5 columns]

In [10]:
print(pd.unique(uriage_data["item_name"]))
print(len(pd.unique(uriage_data["item_name"])))

['商品A' '商品S' '商品Z' '商品V' '商品O' '商品U' '商品L' '商品C' '商品I' '商品R' '商品X' '商品G'
 '商品P' '商品Q' '商品Y' '商品N' '商品W' '商品E' '商品K' '商品B' '商品F' '商品D' '商品M' '商品H'
 '商品T' '商品J']
26

### ノック１５：金額欠損値の補完をしよう

In [11]:
uriage_data.isnull().any(axis=0)

purchase_date     False
item_name         False
item_price         True
customer_name     False
purchase_month    False
dtype: bool

In [12]:
flg_is_null = uriage_data["item_price"].isnull()
for trg in list(uriage_data.loc[flg_is_null, "item_name"].unique()):
    price = uriage_data.loc[(~flg_is_null) & (uriage_data["item_name"] == trg), "item_price"].max()
    uriage_data["item_price"].loc[(flg_is_null) & (uriage_data["item_name"]==trg)] = price
uriage_data.head()

D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:190: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

        purchase_date item_name  item_price customer_name purchase_month
0 2019-06-13 18:02:34       商品A       100.0         深井菜々美         201906
1 2019-07-13 13:05:29       商品S      1900.0          浅田賢二         201907
2 2019-05-11 19:42:07       商品A       100.0          南部慶二         201905
3 2019-02-12 23:40:45       商品Z      2600.0          麻生莉緒         201902
4 2019-04-22 03:09:35       商品A       100.0          平田鉄二         201904

In [13]:
uriage_data.isnull().any(axis=0)

purchase_date     False
item_name         False
item_price        False
customer_name     False
purchase_month    False
dtype: bool

In [14]:
for trg in list(uriage_data["item_name"].sort_values().unique()):
    print(trg + "の最大額：" + str(uriage_data.loc[uriage_data["item_name"]==trg]["item_price"].max()) + "の最小額：" + str(uriage_data.loc[uriage_data["item_name"]==trg]["item_price"].min(skipna=False)))

商品Aの最大額：100.0の最小額：100.0
商品Bの最大額：200.0の最小額：200.0
商品Cの最大額：300.0の最小額：300.0
商品Dの最大額：400.0の最小額：400.0
商品Eの最大額：500.0の最小額：500.0
商品Fの最大額：600.0の最小額：600.0
商品Gの最大額：700.0の最小額：700.0
商品Hの最大額：800.0の最小額：800.0
商品Iの最大額：900.0の最小額：900.0
商品Jの最大額：1000.0の最小額：1000.0
商品Kの最大額：1100.0の最小額：1100.0
商品Lの最大額：1200.0の最小額：1200.0
商品Mの最大額：1300.0の最小額：1300.0
商品Nの最大額：1400.0の最小額：1400.0
商品Oの最大額：1500.0の最小額：1500.0
商品Pの最大額：1600.0の最小額：1600.0
商品Qの最大額：1700.0の最小額：1700.0
商品Rの最大額：1800.0の最小額：1800.0
商品Sの最大額：1900.0の最小額：1900.0
商品Tの最大額：2000.0の最小額：2000.0
商品Uの最大額：2100.0の最小額：2100.0
商品Vの最大額：2200.0の最小額：2200.0
商品Wの最大額：2300.0の最小額：2300.0
商品Xの最大額：2400.0の最小額：2400.0
商品Yの最大額：2500.0の最小額：2500.0
商品Zの最大額：2600.0の最小額：2600.0

### ノック１６：顧客名の揺れを補正しよう

In [15]:
kokyaku_data["顧客名"].head()

0     須賀ひとみ
1    岡田　 敏也
2      芳賀 希
3     荻野  愛
4     栗田 憲一
Name: 顧客名, dtype: object

In [16]:
uriage_data["customer_name"].head()

0    深井菜々美
1     浅田賢二
2     南部慶二
3     麻生莉緒
4     平田鉄二
Name: customer_name, dtype: object

In [17]:
kokyaku_data["顧客名"] = kokyaku_data["顧客名"].str.replace("　", "")
kokyaku_data["顧客名"] = kokyaku_data["顧客名"].str.replace(" ", "")
kokyaku_data["顧客名"].head()

0    須賀ひとみ
1     岡田敏也
2      芳賀希
3      荻野愛
4     栗田憲一
Name: 顧客名, dtype: object

### ノック１７：日付の揺れを補正しよう

In [18]:
flg_is_serial = kokyaku_data["登録日"].astype("str").str.isdigit()
flg_is_serial.sum()

22

In [19]:
fromSerial = pd.to_timedelta(kokyaku_data.loc[flg_is_serial, "登録日"].astype("float"), unit="D") + pd.to_datetime("1900/01/01")
fromSerial

1     2017-02-18
3     2017-05-19
4     2018-01-29
21    2017-07-06
27    2017-06-17
47    2017-01-08
49    2017-07-15
53    2017-04-10
76    2018-03-31
80    2018-01-12
99    2017-06-01
114   2018-06-05
118   2018-01-31
122   2018-04-18
139   2017-05-27
143   2017-03-26
155   2017-01-21
172   2018-03-24
179   2017-01-10
183   2017-07-26
186   2018-07-15
192   2018-06-10
Name: 登録日, dtype: datetime64[ns]

In [20]:
fromString = pd.to_datetime(kokyaku_data.loc[~flg_is_serial, "登録日"])
fromString

0     2018-01-04
2     2018-01-07
5     2017-06-20
6     2018-06-11
7     2017-05-19
8     2018-02-12
9     2017-07-05
10    2018-03-31
11    2017-04-22
12    2018-03-09
13    2017-03-13
14    2018-01-24
15    2017-06-09
16    2018-05-02
17    2017-02-05
18    2018-07-10
19    2017-07-08
20    2018-03-12
22    2018-02-28
23    2017-05-16
24    2018-01-29
25    2017-03-17
26    2018-06-28
28    2018-05-21
29    2017-03-12
30    2018-07-01
31    2017-01-30
32    2018-02-06
33    2017-01-30
34    2018-04-21
         ...
165   2017-02-18
166   2018-03-04
167   2017-03-29
168   2018-07-02
169   2017-06-28
170   2018-05-27
171   2017-02-22
173   2017-02-05
174   2018-01-09
175   2017-06-12
176   2018-02-14
177   2017-04-14
178   2018-03-15
180   2018-07-19
181   2017-05-23
182   2018-05-01
184   2018-05-24
185   2017-04-08
187   2017-05-09
188   2018-07-22
189   2017-07-30
190   2018-06-14
191   2017-01-28
193   2017-05-05
194   2018-02-27
195   2017-06-20
196   2018-06-20
197   2017-04-29
198   2019-04-19
199   2019-04-23
Name: 登録日, Length: 178, dtype: datetime64[ns]

In [21]:
kokyaku_data["登録日"] = pd.concat([fromSerial, fromString])
kokyaku_data

       顧客名           かな  地域                         メールアドレス        登録日
0    須賀ひとみ       すが ひとみ  H市         suga_hitomi@example.com 2018-01-04
1     岡田敏也      おかだ としや  E市       okada_toshiya@example.com 2017-02-18
2      芳賀希       はが のぞみ  A市         haga_nozomi@example.com 2018-01-07
3      荻野愛       おぎの あい  F市            ogino_ai@example.com 2017-05-19
4     栗田憲一     くりた けんいち  E市      kurita_kenichi@example.com 2018-01-29
5     梅沢麻緒      うめざわ まお  A市         umezawa_mao@example.com 2017-06-20
6    相原ひとり     あいはら ひとり  H市       aihara_hitori@example.com 2018-06-11
7     新村丈史     にいむら たけし  B市     niimura_takeshi@example.com 2017-05-19
8    石川まさみ     いしかわ まさみ  G市     ishikawa_masami@example.com 2018-02-12
9     小栗正義     おぐり まさよし  G市     oguri_masayoshi@example.com 2017-07-05
10    大倉晃司     おおくら こうじ  E市        ookura_kouji@example.com 2018-03-31
11    那須蒼甫      なす そうすけ  A市        nasu_sousuke@example.com 2017-04-22
12   清水裕次郎    しみず ゆうじろう  C市    shimizu_yuujirou@example.com 2018-03-09
13   榊原しぼり    さかきばら しぼり  D市  sakakibara_shibori@example.com 2017-03-13
14    高沢美咲     たかさわ みさき  E市     takasawa_misaki@example.com 2018-01-24
15   川島友以乃     かわしま ゆいの  G市     kawashima_yuino@example.com 2017-06-09
16    唐沢景子     からさわ けいこ  D市      karasawa_keiko@example.com 2018-05-02
17    稲田将也      いなだ まさや  G市        inada_masaya@example.com 2017-02-05
18    秋葉あき       あきば あき  H市           akiba_aki@example.com 2018-07-10
19    西脇礼子     にしわき れいこ  H市     nishiwaki_reiko@example.com 2017-07-08
20   内村まさみ     うちむら まさみ  A市     uchimura_masami@example.com 2018-03-12
21     進藤瞬     しんどう しゅん  A市       shinndou_shun@example.com 2017-07-06
22     小口豊      おぐち ゆたか  H市       oguchi_yutaka@example.com 2018-02-28
23   笹原しぼり     ささはら しぼり  E市    sasahara_shibori@example.com 2017-05-16
24   岩佐孝太郎    いわさ こうたろう  D市      iwasa_koutarou@example.com 2018-01-29
25    河村由樹      かわむら ゆき  C市       kawamura_yuki@example.com 2017-03-17
26    菅原誠治     すがわら せいじ  C市      sugawara_seiji@example.com 2018-06-28
27     榎本薫     えのもと かおる  C市       enomoto_kaoru@example.com 2017-06-17
28    高梨結衣      たかなし ゆい  C市       takanashi_yui@example.com 2018-05-21
29     鶴岡薫     つるおか かおる  F市      tsuruoka_kaoru@example.com 2017-03-12
..     ...          ...  ..                             ...        ...
170   岩井莉緒       いわい りお  F市            iwai_rio@example.com 2018-05-27
171  大崎ヒカル     おおさき ひかる  E市       oosaki_hikaru@example.com 2017-02-22
172  矢沢恵梨香      やざわ えりか  G市        yazawa_erika@example.com 2018-03-24
173   石田郁恵      いしだ いくえ  B市         ishida_ikue@example.com 2017-02-05
174   荻野愛菜      おぎの あいな  B市          ogino_aina@example.com 2018-01-09
175   香椎優一     かしい ゆういち  H市      kashii_yuuichi@example.com 2017-06-12
176  黄川田博之    きかわだ ひろゆき  C市   kikawada_hiroyuki@example.com 2018-02-14
177   井村俊二     いむら しゅんじ  D市        imura_shunji@example.com 2017-04-14
178  植木沙知絵      うえき さちえ  F市         ueki_sachie@example.com 2018-03-15
179   小松隼士     こまつ しゅんじ  C市      komatsu_shunji@example.com 2017-01-10
180    松村聡     まつむら さとし  G市   matsumura_satoshi@example.com 2018-07-19
181   平賀一哉      ひらが かずや  B市       hiraga_kazuya@example.com 2017-05-23
182    手塚進      てづか すすむ  A市       teduka_susumu@example.com 2018-05-01
183    磯野希      いその のぞみ  B市        isono_nozomi@example.com 2017-07-26
184   白井俊二     しらい しゅんじ  H市       shirai_shunji@example.com 2018-05-24
185   笹川照生     ささがわ てるお  F市      sasagawa_teruo@example.com 2017-04-08
186   芦田博之     あしだ ひろゆき  E市     ashida_hiroyuki@example.com 2018-07-15
187   大地礼子      おおち れいこ  E市         oochi_reiko@example.com 2017-05-09
188    小町瞬      こまち しゅん  D市        komachi_shun@example.com 2018-07-22
189  水野メイサ      みずの めいさ  D市        mizuno_meisa@example.com 2017-07-30
190    板橋隆     いたばし たかし  B市    itabashi_takashi@example.com 2018-06-14
191   綾瀬俊介    あやせ しゅんすけ  B市      ayase_shunsuke@example.com 2017-01-28
192   和泉直人     わいずみ なおと  H市       waizumi_naoto@example.com 2018-06-10
193   堀北雅彦    ほりきた まさひこ  H市   horikita_masahiko@example.com 2017-05-05
194    唐沢涼     からさわ りょう  H市       karasawa_ryou@example.com 2018-02-27
195   川上りえ      かわかみ りえ  G市        kawakami_rie@example.com 2017-06-20
196   小松季衣      こまつ としえ  E市      komatsu_toshie@example.com 2018-06-20
197   白鳥りえ      しらとり りえ  F市       shiratori_rie@example.com 2017-04-29
198  大西隆之介  おおにし りゅうのすけ  H市  oonishi_ryuunosuke@example.com 2019-04-19
199   福井美希       ふくい みき  D市         fukui_miki1@example.com 2019-04-23

[200 rows x 5 columns]

In [22]:
kokyaku_data["登録年月"] = kokyaku_data["登録日"].dt.strftime("%Y%m")
rslt = kokyaku_data.groupby("登録年月").count()["顧客名"]
print(rslt)
print(len(kokyaku_data))

登録年月
201701    15
201702    11
201703    14
201704    15
201705    13
201706    14
201707    17
201801    13
201802    15
201803    17
201804     5
201805    19
201806    13
201807    17
201904     2
Name: 顧客名, dtype: int64
200

In [23]:
flg_is_serial = kokyaku_data["登録日"].astype("str").str.isdigit()
flg_is_serial.sum()

0

### ノック１８：顧客名をキーに２つのデータを結合(ジョイン)しよう

In [24]:
join_data = pd.merge(uriage_data, kokyaku_data, left_on="customer_name", right_on="顧客名", how="left")
join_data = join_data.drop("customer_name", axis=1)
join_data

,purchase_date,item_name,item_price,purchase_month,顧客名,かな,地域,メールアドレス,登録日,登録年月
0,2019-06-13 18:02:34,商品A,100.0,201906,深井菜々美,ふかい ななみ,C市,fukai_nanami@example.com,2017-01-26,201701
1,2019-07-13 13:05:29,商品S,1900.0,201907,浅田賢二,あさだ けんじ,C市,asada_kenji@example.com,2018-04-07,201804
2,2019-05-11 19:42:07,商品A,100.0,201905,南部慶二,なんぶ けいじ,A市,nannbu_keiji@example.com,2018-06-19,201806
3,2019-02-12 23:40:45,商品Z,2600.0,201902,麻生莉緒,あそう りお,D市,asou_rio@example.com,2018-07-22,201807
4,2019-04-22 03:09:35,商品A,100.0,201904,平田鉄二,ひらた てつじ,D市,hirata_tetsuji@example.com,2017-06-07,201706
5,2019-03-20 19:16:01,商品S,1900.0,201903,堀江佑,ほりえ たすく,H市,horie_tasuku@example.com,2018-05-14,201805
6,2019-05-18 19:16:53,商品A,100.0,201905,深井照生,ふかい てるお,A市,fukai_teruo@example.com,2018-02-21,201802
7,2019-04-18 00:14:21,商品V,2200.0,201904,牧田玲那,まきた れな,A市,makita_rena@example.com,2017-05-13,201705
8,2019-01-10 15:51:01,商品O,1500.0,201901,堀北雅彦,ほりきた まさひこ,H市,horikita_masahiko@example.com,2017-05-05,201705
9,2019-01-28 10:47:03,商品A,100.0,201901,大地礼子,おおち れいこ,E市,oochi_reiko@example.com,2017-05-09,201705
10,2019-06-21 01:54:35,商品U,2100.0,201906,矢部惇,やべ じゅん,A市,yabe_jun@example.com,2018-05-20,201805
11,2019-06-08 11:32:25,商品L,1200.0,201906,岡田敏也,おかだ としや,E市,okada_toshiya@example.com,2017-02-18,201702
12,2019-04-08 02:00:44,商品V,2200.0,201904,浅見広司,あさみ こうじ,D市,asami_kouji@example.com,2018-06-05,201806
13,2019-06-19 09:50:52,商品O,1500.0,201906,熊井憲史,くまい のりひと,A市,kumai_norihito@example.com,2017-03-29,201703
14,2019-06-11 12:57:24,商品A,100.0,201906,黄川田博之,きかわだ ひろゆき,C市,kikawada_hiroyuki@example.com,2018-02-14,201802
15,2019-04-21 00:11:43,商品C,300.0,201904,尾形小雁,おがた こがん,B市,ogata_kogan@example.com,2017-03-15,201703
16,2019-03-28 23:24:46,商品V,2200.0,201903,神原美嘉,かんばら みか,D市,kannbara_mika@example.com,2017-03-23,201703
17,2019-04-06 12:00:53,商品I,900.0,201904,若杉徹,わかすぎ とおる,G市,wakasugi_tohru@example.com,2017-03-26,201703
18,2019-07-16 05:55:57,商品R,1800.0,201907,石渡小雁,いしわたり こがん,D市,ishiwatari_kogan@example.com,2017-07-28,201707
19,2019-07-03 07:04:05,商品X,2400.0,201907,東光博,ひがし みつひろ,A市,higashi_mitsuhiro@example.com,2018-02-06,201802
20,2019-07-05 10:49:13,商品O,1500.0,201907,日野夏希,ひの なつき,A市,hino_natsuki@example.com,2017-05-23,201705
21,2019-06-10 19:07:23,商品G,700.0,201906,黒谷長利,くろたに ながとし,A市,kurotani_nagatoshi@example.com,2017-04-27,201704
22,2019-07-10 20:28:12,商品X,2400.0,201907,田辺光洋,たなべ みつひろ,A市,tanabe_mitsuhiro@example.com,2018-07-04,201807
23,2019-07-10 12:44:10,商品R,1800.0,201907,戸塚美幸,とづか みゆき,H市,toduka_miyuki@example.com,2017-01-30,201701
24,2019-02-14 01:30:09,商品P,1600.0,201902,榊原しぼり,さかきばら しぼり,D市,sakakibara_shibori@example.com,2017-03-13,201703
25,2019-04-18 01:50:16,商品Q,1700.0,201904,浅田賢二,あさだ けんじ,C市,asada_kenji@example.com,2018-04-07,201804
26,2019-05-16 04:45:21,商品Y,2500.0,201905,明石家明,あかしや あきら,B市,akashiya_akira@example.com,2018-02-13,201802
27,2019-05-26 10:58:00,商品P,1600.0,201905,手塚進,てづか すすむ,A市,teduka_susumu@example.com,2018-05-01,201805
28,2019-01-04 12:05:04,商品P,1600.0,201901,堀江佑,ほりえ たすく,H市,horie_tasuku@example.com,2018-05-14,201805
29,2019-02-11 18:32:05,商品R,1800.0,201902,荻野愛,おぎの あい,F市,ogino_ai@example.com,2017-05-19,201705
...,...,...,...,...,...,...,...,...,...,...
2969,2019-02-01 03:48:49,商品O,1500.0,201902,河内さとみ,かわうち さとみ,E市,kawauchi_satomi@example.com,2017-01-21,201701
2970,2019-03-15 11:17:20,商品L,1200.0,201903,松川綾女,まつかわ あやめ,E市,matsukawa_ayame@example.com,2018-07-23,201807
2971,2019-02-02 04:52:12,商品S,1900.0,201902,井上桃子,いのうえ ももこ,F市,inoue_momoko@example.com,2018-06-18,201806
2972,2019-04-30 19:47:44,商品R,1800.0,201904,杉下悟志,すぎした さとし,E市,sugishita_satoshi@example.com,2018-02-17,201802
2973,2019-07-13 21:38:11,商品A,100.0,201907,大地礼子,おおち れいこ,E市,oochi_reiko@example.com,2017-05-09,201705
2974,2019-02-04 17:08:40,商品P,1600.0,201902,岡慶太,おか けいた,C市,oka_keita@example.com,2018-07-22,201807
2975,2019-07-21 10:36:03,商品Y,2500.0,201907,矢部美幸,やべ みゆき,F市,yabe_miyuki@example.com,2017-05-27,201705
2976,2019-07-11 00:11:36,商品L,1200.0,201907,井本マサカズ,いもと まさかず,C市,imoto_masakazu@example.com,2017-04-06,201704
2977,2019-03-02 20:55:58,商品X,2400.0,201903,合田光,あいだ ひかる,D市,aida_hikaru@example.com,2018-05-22,201805
2978,2019-04-06 21:20:36,商品N,1400.0,201904,浅田賢二,あさだ けんじ,C市,asada_kenji@example.com,2018-04-07,201804
2979,2019-03-09 17:26:00,商品N,1400.0,201903,深田信輔,ふかだ しんすけ,G市,fukada_shinsuke@example.com,2017-07-07,201707
2980,2019-07-01 02:15:47,商品P,1600.0,201907,矢部美幸,やべ みゆき,F市,yabe_miyuki@example.com,2017-05-27,201705
2981,2019-04-26 22:17:47,商品R,1800.0,201904,奥光洋,おく みつひろ,A市,oku_mitsuhiro@example.com,2018-01-08,201801
2982,2019-02-18 16:53:38,商品L,1200.0,201902,篠山雅功,しのやま まさとし,B市,shinoyama_masatoshi@example.com,2018-07-02,201807
2983,2019-05-09 00:44:58,商品H,800.0,201905,さだ千佳子,さだ ちかこ,H市,sada_chikako@example.com,2017-07-01,201707
2984,2019-03-06 06:16:05,商品G,700.0,201903,笹川照生,ささがわ てるお,F市,sasagawa_teruo@example.com,2017-04-08,201704
2985,2019-03-06 22:30:55,商品X,2400.0,201903,岩沢那奈,いわさわ なな,H市,iwasawa_nana@example.com,2017-07-13,201707
2986,2019-03-12 19:34:15,商品C,300.0,201903,熊倉明日,くまくら めいび,G市,kumakura_meibi@example.com,2018-05-07,201805
2987,2019-01-04 13:05:29,商品K,1100.0,201901,松谷愛子,まつたに あいこ,D市,matsutani_aiko@example.com,2018-07-30,201807
2988,2019-01-23 07:08:04,商品R,1800.0,201901,矢部惇,やべ じゅん,A市,yabe_jun@example.com,2018-05-20,201805
2989,2019-05-19 03:20:24,商品M,1300.0,201905,植村遥,うえむら はるか,A市,uemura_haruka@example.com,2018-01-06,201801
2990,2019-07-16 11:34:22,商品O,1500.0,201907,榎本薫,えのもと かおる,C市,enomoto_kaoru@example.com,2017-06-17,201706
2991,2019-02-18 14:36:49,商品W,2300.0,201902,尾上勝久,おがみ かつひさ,D市,ogami_katsuhisa@example.com,2017-07-20,201707
2992,2019-07-27 10:13:13,商品C,300.0,201907,植木沙知絵,うえき さちえ,F市,ueki_sachie@example.com,2018-03-15,201803
2993,2019-01-25 03:57:54,商品C,300.0,201901,白鳥りえ,しらとり りえ,F市,shiratori_rie@example.com,2017-04-29,201704
2994,2019-02-15 02:56:39,商品Y,2500.0,201902,福島友也,ふくしま ともや,B市,fukushima_tomoya@example.com,2017-07-01,201707
2995,2019-06-22 04:03:43,商品M,1300.0,201906,大倉晃司,おおくら こうじ,E市,ookura_kouji@example.com,2018-03-31,201803
2996,2019-03-29 11:14:05,商品Q,1700.0,201903,尾形小雁,おがた こがん,B市,ogata_kogan@example.com,2017-03-15,201703
2997,2019-07-14 12:56:49,商品H,800.0,201907,芦田博之,あしだ ひろゆき,E市,ashida_hiroyuki@example.com,2018-07-15,201807
2998,2019-07-21 00:31:36,商品D,400.0,201907,石田郁恵,いしだ いくえ,B市,ishida_ikue@example.com,2017-02-05,201702

### ノック１９：クレンジングしたデータをダンプしよう

In [25]:
dump_data = join_data[["purchase_date", "purchase_month", "item_name", "item_price", "顧客名", "かな", "地域", "メールアドレス", "登録日"]]
dump_data

,purchase_date,purchase_month,item_name,item_price,顧客名,かな,地域,メールアドレス,登録日
0,2019-06-13 18:02:34,201906,商品A,100.0,深井菜々美,ふかい ななみ,C市,fukai_nanami@example.com,2017-01-26
1,2019-07-13 13:05:29,201907,商品S,1900.0,浅田賢二,あさだ けんじ,C市,asada_kenji@example.com,2018-04-07
2,2019-05-11 19:42:07,201905,商品A,100.0,南部慶二,なんぶ けいじ,A市,nannbu_keiji@example.com,2018-06-19
3,2019-02-12 23:40:45,201902,商品Z,2600.0,麻生莉緒,あそう りお,D市,asou_rio@example.com,2018-07-22
4,2019-04-22 03:09:35,201904,商品A,100.0,平田鉄二,ひらた てつじ,D市,hirata_tetsuji@example.com,2017-06-07
5,2019-03-20 19:16:01,201903,商品S,1900.0,堀江佑,ほりえ たすく,H市,horie_tasuku@example.com,2018-05-14
6,2019-05-18 19:16:53,201905,商品A,100.0,深井照生,ふかい てるお,A市,fukai_teruo@example.com,2018-02-21
7,2019-04-18 00:14:21,201904,商品V,2200.0,牧田玲那,まきた れな,A市,makita_rena@example.com,2017-05-13
8,2019-01-10 15:51:01,201901,商品O,1500.0,堀北雅彦,ほりきた まさひこ,H市,horikita_masahiko@example.com,2017-05-05
9,2019-01-28 10:47:03,201901,商品A,100.0,大地礼子,おおち れいこ,E市,oochi_reiko@example.com,2017-05-09
10,2019-06-21 01:54:35,201906,商品U,2100.0,矢部惇,やべ じゅん,A市,yabe_jun@example.com,2018-05-20
11,2019-06-08 11:32:25,201906,商品L,1200.0,岡田敏也,おかだ としや,E市,okada_toshiya@example.com,2017-02-18
12,2019-04-08 02:00:44,201904,商品V,2200.0,浅見広司,あさみ こうじ,D市,asami_kouji@example.com,2018-06-05
13,2019-06-19 09:50:52,201906,商品O,1500.0,熊井憲史,くまい のりひと,A市,kumai_norihito@example.com,2017-03-29
14,2019-06-11 12:57:24,201906,商品A,100.0,黄川田博之,きかわだ ひろゆき,C市,kikawada_hiroyuki@example.com,2018-02-14
15,2019-04-21 00:11:43,201904,商品C,300.0,尾形小雁,おがた こがん,B市,ogata_kogan@example.com,2017-03-15
16,2019-03-28 23:24:46,201903,商品V,2200.0,神原美嘉,かんばら みか,D市,kannbara_mika@example.com,2017-03-23
17,2019-04-06 12:00:53,201904,商品I,900.0,若杉徹,わかすぎ とおる,G市,wakasugi_tohru@example.com,2017-03-26
18,2019-07-16 05:55:57,201907,商品R,1800.0,石渡小雁,いしわたり こがん,D市,ishiwatari_kogan@example.com,2017-07-28
19,2019-07-03 07:04:05,201907,商品X,2400.0,東光博,ひがし みつひろ,A市,higashi_mitsuhiro@example.com,2018-02-06
20,2019-07-05 10:49:13,201907,商品O,1500.0,日野夏希,ひの なつき,A市,hino_natsuki@example.com,2017-05-23
21,2019-06-10 19:07:23,201906,商品G,700.0,黒谷長利,くろたに ながとし,A市,kurotani_nagatoshi@example.com,2017-04-27
22,2019-07-10 20:28:12,201907,商品X,2400.0,田辺光洋,たなべ みつひろ,A市,tanabe_mitsuhiro@example.com,2018-07-04
23,2019-07-10 12:44:10,201907,商品R,1800.0,戸塚美幸,とづか みゆき,H市,toduka_miyuki@example.com,2017-01-30
24,2019-02-14 01:30:09,201902,商品P,1600.0,榊原しぼり,さかきばら しぼり,D市,sakakibara_shibori@example.com,2017-03-13
25,2019-04-18 01:50:16,201904,商品Q,1700.0,浅田賢二,あさだ けんじ,C市,asada_kenji@example.com,2018-04-07
26,2019-05-16 04:45:21,201905,商品Y,2500.0,明石家明,あかしや あきら,B市,akashiya_akira@example.com,2018-02-13
27,2019-05-26 10:58:00,201905,商品P,1600.0,手塚進,てづか すすむ,A市,teduka_susumu@example.com,2018-05-01
28,2019-01-04 12:05:04,201901,商品P,1600.0,堀江佑,ほりえ たすく,H市,horie_tasuku@example.com,2018-05-14
29,2019-02-11 18:32:05,201902,商品R,1800.0,荻野愛,おぎの あい,F市,ogino_ai@example.com,2017-05-19
...,...,...,...,...,...,...,...,...,...
2969,2019-02-01 03:48:49,201902,商品O,1500.0,河内さとみ,かわうち さとみ,E市,kawauchi_satomi@example.com,2017-01-21
2970,2019-03-15 11:17:20,201903,商品L,1200.0,松川綾女,まつかわ あやめ,E市,matsukawa_ayame@example.com,2018-07-23
2971,2019-02-02 04:52:12,201902,商品S,1900.0,井上桃子,いのうえ ももこ,F市,inoue_momoko@example.com,2018-06-18
2972,2019-04-30 19:47:44,201904,商品R,1800.0,杉下悟志,すぎした さとし,E市,sugishita_satoshi@example.com,2018-02-17
2973,2019-07-13 21:38:11,201907,商品A,100.0,大地礼子,おおち れいこ,E市,oochi_reiko@example.com,2017-05-09
2974,2019-02-04 17:08:40,201902,商品P,1600.0,岡慶太,おか けいた,C市,oka_keita@example.com,2018-07-22
2975,2019-07-21 10:36:03,201907,商品Y,2500.0,矢部美幸,やべ みゆき,F市,yabe_miyuki@example.com,2017-05-27
2976,2019-07-11 00:11:36,201907,商品L,1200.0,井本マサカズ,いもと まさかず,C市,imoto_masakazu@example.com,2017-04-06
2977,2019-03-02 20:55:58,201903,商品X,2400.0,合田光,あいだ ひかる,D市,aida_hikaru@example.com,2018-05-22
2978,2019-04-06 21:20:36,201904,商品N,1400.0,浅田賢二,あさだ けんじ,C市,asada_kenji@example.com,2018-04-07
2979,2019-03-09 17:26:00,201903,商品N,1400.0,深田信輔,ふかだ しんすけ,G市,fukada_shinsuke@example.com,2017-07-07
2980,2019-07-01 02:15:47,201907,商品P,1600.0,矢部美幸,やべ みゆき,F市,yabe_miyuki@example.com,2017-05-27
2981,2019-04-26 22:17:47,201904,商品R,1800.0,奥光洋,おく みつひろ,A市,oku_mitsuhiro@example.com,2018-01-08
2982,2019-02-18 16:53:38,201902,商品L,1200.0,篠山雅功,しのやま まさとし,B市,shinoyama_masatoshi@example.com,2018-07-02
2983,2019-05-09 00:44:58,201905,商品H,800.0,さだ千佳子,さだ ちかこ,H市,sada_chikako@example.com,2017-07-01
2984,2019-03-06 06:16:05,201903,商品G,700.0,笹川照生,ささがわ てるお,F市,sasagawa_teruo@example.com,2017-04-08
2985,2019-03-06 22:30:55,201903,商品X,2400.0,岩沢那奈,いわさわ なな,H市,iwasawa_nana@example.com,2017-07-13
2986,2019-03-12 19:34:15,201903,商品C,300.0,熊倉明日,くまくら めいび,G市,kumakura_meibi@example.com,2018-05-07
2987,2019-01-04 13:05:29,201901,商品K,1100.0,松谷愛子,まつたに あいこ,D市,matsutani_aiko@example.com,2018-07-30
2988,2019-01-23 07:08:04,201901,商品R,1800.0,矢部惇,やべ じゅん,A市,yabe_jun@example.com,2018-05-20
2989,2019-05-19 03:20:24,201905,商品M,1300.0,植村遥,うえむら はるか,A市,uemura_haruka@example.com,2018-01-06
2990,2019-07-16 11:34:22,201907,商品O,1500.0,榎本薫,えのもと かおる,C市,enomoto_kaoru@example.com,2017-06-17
2991,2019-02-18 14:36:49,201902,商品W,2300.0,尾上勝久,おがみ かつひさ,D市,ogami_katsuhisa@example.com,2017-07-20
2992,2019-07-27 10:13:13,201907,商品C,300.0,植木沙知絵,うえき さちえ,F市,ueki_sachie@example.com,2018-03-15
2993,2019-01-25 03:57:54,201901,商品C,300.0,白鳥りえ,しらとり りえ,F市,shiratori_rie@example.com,2017-04-29
2994,2019-02-15 02:56:39,201902,商品Y,2500.0,福島友也,ふくしま ともや,B市,fukushima_tomoya@example.com,2017-07-01
2995,2019-06-22 04:03:43,201906,商品M,1300.0,大倉晃司,おおくら こうじ,E市,ookura_kouji@example.com,2018-03-31
2996,2019-03-29 11:14:05,201903,商品Q,1700.0,尾形小雁,おがた こがん,B市,ogata_kogan@example.com,2017-03-15
2997,2019-07-14 12:56:49,201907,商品H,800.0,芦田博之,あしだ ひろゆき,E市,ashida_hiroyuki@example.com,2018-07-15
2998,2019-07-21 00:31:36,201907,商品D,400.0,石田郁恵,いしだ いくえ,B市,ishida_ikue@example.com,2017-02-05

In [26]:
dump_data.to_csv("dump_data.csv", index=False)

### ノック２０：データを集計しよう

In [27]:
import_data = pd.read_csv("dump_data.csv")
import_data

,purchase_date,purchase_month,item_name,item_price,顧客名,かな,地域,メールアドレス,登録日
0,2019-06-13 18:02:34,201906,商品A,100.0,深井菜々美,ふかい ななみ,C市,fukai_nanami@example.com,2017-01-26 00:00:00
1,2019-07-13 13:05:29,201907,商品S,1900.0,浅田賢二,あさだ けんじ,C市,asada_kenji@example.com,2018-04-07 00:00:00
2,2019-05-11 19:42:07,201905,商品A,100.0,南部慶二,なんぶ けいじ,A市,nannbu_keiji@example.com,2018-06-19 00:00:00
3,2019-02-12 23:40:45,201902,商品Z,2600.0,麻生莉緒,あそう りお,D市,asou_rio@example.com,2018-07-22 00:00:00
4,2019-04-22 03:09:35,201904,商品A,100.0,平田鉄二,ひらた てつじ,D市,hirata_tetsuji@example.com,2017-06-07 00:00:00
5,2019-03-20 19:16:01,201903,商品S,1900.0,堀江佑,ほりえ たすく,H市,horie_tasuku@example.com,2018-05-14 00:00:00
6,2019-05-18 19:16:53,201905,商品A,100.0,深井照生,ふかい てるお,A市,fukai_teruo@example.com,2018-02-21 00:00:00
7,2019-04-18 00:14:21,201904,商品V,2200.0,牧田玲那,まきた れな,A市,makita_rena@example.com,2017-05-13 00:00:00
8,2019-01-10 15:51:01,201901,商品O,1500.0,堀北雅彦,ほりきた まさひこ,H市,horikita_masahiko@example.com,2017-05-05 00:00:00
9,2019-01-28 10:47:03,201901,商品A,100.0,大地礼子,おおち れいこ,E市,oochi_reiko@example.com,2017-05-09 00:00:00
10,2019-06-21 01:54:35,201906,商品U,2100.0,矢部惇,やべ じゅん,A市,yabe_jun@example.com,2018-05-20 00:00:00
11,2019-06-08 11:32:25,201906,商品L,1200.0,岡田敏也,おかだ としや,E市,okada_toshiya@example.com,2017-02-18 00:00:00
12,2019-04-08 02:00:44,201904,商品V,2200.0,浅見広司,あさみ こうじ,D市,asami_kouji@example.com,2018-06-05 00:00:00
13,2019-06-19 09:50:52,201906,商品O,1500.0,熊井憲史,くまい のりひと,A市,kumai_norihito@example.com,2017-03-29 00:00:00
14,2019-06-11 12:57:24,201906,商品A,100.0,黄川田博之,きかわだ ひろゆき,C市,kikawada_hiroyuki@example.com,2018-02-14 00:00:00
15,2019-04-21 00:11:43,201904,商品C,300.0,尾形小雁,おがた こがん,B市,ogata_kogan@example.com,2017-03-15 00:00:00
16,2019-03-28 23:24:46,201903,商品V,2200.0,神原美嘉,かんばら みか,D市,kannbara_mika@example.com,2017-03-23 00:00:00
17,2019-04-06 12:00:53,201904,商品I,900.0,若杉徹,わかすぎ とおる,G市,wakasugi_tohru@example.com,2017-03-26 00:00:00
18,2019-07-16 05:55:57,201907,商品R,1800.0,石渡小雁,いしわたり こがん,D市,ishiwatari_kogan@example.com,2017-07-28 00:00:00
19,2019-07-03 07:04:05,201907,商品X,2400.0,東光博,ひがし みつひろ,A市,higashi_mitsuhiro@example.com,2018-02-06 00:00:00
20,2019-07-05 10:49:13,201907,商品O,1500.0,日野夏希,ひの なつき,A市,hino_natsuki@example.com,2017-05-23 00:00:00
21,2019-06-10 19:07:23,201906,商品G,700.0,黒谷長利,くろたに ながとし,A市,kurotani_nagatoshi@example.com,2017-04-27 00:00:00
22,2019-07-10 20:28:12,201907,商品X,2400.0,田辺光洋,たなべ みつひろ,A市,tanabe_mitsuhiro@example.com,2018-07-04 00:00:00
23,2019-07-10 12:44:10,201907,商品R,1800.0,戸塚美幸,とづか みゆき,H市,toduka_miyuki@example.com,2017-01-30 00:00:00
24,2019-02-14 01:30:09,201902,商品P,1600.0,榊原しぼり,さかきばら しぼり,D市,sakakibara_shibori@example.com,2017-03-13 00:00:00
25,2019-04-18 01:50:16,201904,商品Q,1700.0,浅田賢二,あさだ けんじ,C市,asada_kenji@example.com,2018-04-07 00:00:00
26,2019-05-16 04:45:21,201905,商品Y,2500.0,明石家明,あかしや あきら,B市,akashiya_akira@example.com,2018-02-13 00:00:00
27,2019-05-26 10:58:00,201905,商品P,1600.0,手塚進,てづか すすむ,A市,teduka_susumu@example.com,2018-05-01 00:00:00
28,2019-01-04 12:05:04,201901,商品P,1600.0,堀江佑,ほりえ たすく,H市,horie_tasuku@example.com,2018-05-14 00:00:00
29,2019-02-11 18:32:05,201902,商品R,1800.0,荻野愛,おぎの あい,F市,ogino_ai@example.com,2017-05-19 00:00:00
...,...,...,...,...,...,...,...,...,...
2969,2019-02-01 03:48:49,201902,商品O,1500.0,河内さとみ,かわうち さとみ,E市,kawauchi_satomi@example.com,2017-01-21 00:00:00
2970,2019-03-15 11:17:20,201903,商品L,1200.0,松川綾女,まつかわ あやめ,E市,matsukawa_ayame@example.com,2018-07-23 00:00:00
2971,2019-02-02 04:52:12,201902,商品S,1900.0,井上桃子,いのうえ ももこ,F市,inoue_momoko@example.com,2018-06-18 00:00:00
2972,2019-04-30 19:47:44,201904,商品R,1800.0,杉下悟志,すぎした さとし,E市,sugishita_satoshi@example.com,2018-02-17 00:00:00
2973,2019-07-13 21:38:11,201907,商品A,100.0,大地礼子,おおち れいこ,E市,oochi_reiko@example.com,2017-05-09 00:00:00
2974,2019-02-04 17:08:40,201902,商品P,1600.0,岡慶太,おか けいた,C市,oka_keita@example.com,2018-07-22 00:00:00
2975,2019-07-21 10:36:03,201907,商品Y,2500.0,矢部美幸,やべ みゆき,F市,yabe_miyuki@example.com,2017-05-27 00:00:00
2976,2019-07-11 00:11:36,201907,商品L,1200.0,井本マサカズ,いもと まさかず,C市,imoto_masakazu@example.com,2017-04-06 00:00:00
2977,2019-03-02 20:55:58,201903,商品X,2400.0,合田光,あいだ ひかる,D市,aida_hikaru@example.com,2018-05-22 00:00:00
2978,2019-04-06 21:20:36,201904,商品N,1400.0,浅田賢二,あさだ けんじ,C市,asada_kenji@example.com,2018-04-07 00:00:00
2979,2019-03-09 17:26:00,201903,商品N,1400.0,深田信輔,ふかだ しんすけ,G市,fukada_shinsuke@example.com,2017-07-07 00:00:00
2980,2019-07-01 02:15:47,201907,商品P,1600.0,矢部美幸,やべ みゆき,F市,yabe_miyuki@example.com,2017-05-27 00:00:00
2981,2019-04-26 22:17:47,201904,商品R,1800.0,奥光洋,おく みつひろ,A市,oku_mitsuhiro@example.com,2018-01-08 00:00:00
2982,2019-02-18 16:53:38,201902,商品L,1200.0,篠山雅功,しのやま まさとし,B市,shinoyama_masatoshi@example.com,2018-07-02 00:00:00
2983,2019-05-09 00:44:58,201905,商品H,800.0,さだ千佳子,さだ ちかこ,H市,sada_chikako@example.com,2017-07-01 00:00:00
2984,2019-03-06 06:16:05,201903,商品G,700.0,笹川照生,ささがわ てるお,F市,sasagawa_teruo@example.com,2017-04-08 00:00:00
2985,2019-03-06 22:30:55,201903,商品X,2400.0,岩沢那奈,いわさわ なな,H市,iwasawa_nana@example.com,2017-07-13 00:00:00
2986,2019-03-12 19:34:15,201903,商品C,300.0,熊倉明日,くまくら めいび,G市,kumakura_meibi@example.com,2018-05-07 00:00:00
2987,2019-01-04 13:05:29,201901,商品K,1100.0,松谷愛子,まつたに あいこ,D市,matsutani_aiko@example.com,2018-07-30 00:00:00
2988,2019-01-23 07:08:04,201901,商品R,1800.0,矢部惇,やべ じゅん,A市,yabe_jun@example.com,2018-05-20 00:00:00
2989,2019-05-19 03:20:24,201905,商品M,1300.0,植村遥,うえむら はるか,A市,uemura_haruka@example.com,2018-01-06 00:00:00
2990,2019-07-16 11:34:22,201907,商品O,1500.0,榎本薫,えのもと かおる,C市,enomoto_kaoru@example.com,2017-06-17 00:00:00
2991,2019-02-18 14:36:49,201902,商品W,2300.0,尾上勝久,おがみ かつひさ,D市,ogami_katsuhisa@example.com,2017-07-20 00:00:00
2992,2019-07-27 10:13:13,201907,商品C,300.0,植木沙知絵,うえき さちえ,F市,ueki_sachie@example.com,2018-03-15 00:00:00
2993,2019-01-25 03:57:54,201901,商品C,300.0,白鳥りえ,しらとり りえ,F市,shiratori_rie@example.com,2017-04-29 00:00:00
2994,2019-02-15 02:56:39,201902,商品Y,2500.0,福島友也,ふくしま ともや,B市,fukushima_tomoya@example.com,2017-07-01 00:00:00
2995,2019-06-22 04:03:43,201906,商品M,1300.0,大倉晃司,おおくら こうじ,E市,ookura_kouji@example.com,2018-03-31 00:00:00
2996,2019-03-29 11:14:05,201903,商品Q,1700.0,尾形小雁,おがた こがん,B市,ogata_kogan@example.com,2017-03-15 00:00:00
2997,2019-07-14 12:56:49,201907,商品H,800.0,芦田博之,あしだ ひろゆき,E市,ashida_hiroyuki@example.com,2018-07-15 00:00:00
2998,2019-07-21 00:31:36,201907,商品D,400.0,石田郁恵,いしだ いくえ,B市,ishida_ikue@example.com,2017-02-05 00:00:00

In [28]:
byItem = import_data.pivot_table(index="purchase_month", columns="item_name", aggfunc="size", fill_value=0)
byItem

item_name,商品A,商品B,商品C,商品D,商品E,商品F,商品G,商品H,商品I,商品J,...,商品Q,商品R,商品S,商品T,商品U,商品V,商品W,商品X,商品Y,商品Z
purchase_month,,,,,,,,,,,,,,,,,,,,,
201901,18,13,19,17,18,15,11,16,18,17,...,17,21,20,17,7,22,13,14,10,0
201902,19,14,26,21,16,14,14,17,12,14,...,22,22,22,23,19,22,24,16,11,1
201903,17,21,20,17,9,27,14,18,12,16,...,23,16,20,12,23,18,16,21,16,0
201904,17,19,24,20,18,17,14,11,18,13,...,20,20,16,16,11,15,14,16,20,0
201905,24,14,16,14,19,18,23,15,16,11,...,13,22,18,16,16,9,21,16,20,0
201906,24,12,11,19,13,18,15,13,19,22,...,15,16,21,12,18,20,17,15,13,0
201907,20,20,17,17,12,17,19,19,19,23,...,15,19,23,21,13,28,16,18,12,0

In [29]:
byPrice = import_data.pivot_table(index="purchase_month", columns="item_name", values="item_price", aggfunc="sum", fill_value=0)
byPrice

item_name,商品A,商品B,商品C,商品D,商品E,商品F,商品G,商品H,商品I,商品J,...,商品Q,商品R,商品S,商品T,商品U,商品V,商品W,商品X,商品Y,商品Z
purchase_month,,,,,,,,,,,,,,,,,,,,,
201901,1800,2600,5700,6800,9000,9000,7700,12800,16200,17000,...,28900,37800,38000,34000,14700,48400,29900,33600,25000,0
201902,1900,2800,7800,8400,8000,8400,9800,13600,10800,14000,...,37400,39600,41800,46000,39900,48400,55200,38400,27500,2600
201903,1700,4200,6000,6800,4500,16200,9800,14400,10800,16000,...,39100,28800,38000,24000,48300,39600,36800,50400,40000,0
201904,1700,3800,7200,8000,9000,10200,9800,8800,16200,13000,...,34000,36000,30400,32000,23100,33000,32200,38400,50000,0
201905,2400,2800,4800,5600,9500,10800,16100,12000,14400,11000,...,22100,39600,34200,32000,33600,19800,48300,38400,50000,0
201906,2400,2400,3300,7600,6500,10800,10500,10400,17100,22000,...,25500,28800,39900,24000,37800,44000,39100,36000,32500,0
201907,2000,4000,5100,6800,6000,10200,13300,15200,17100,23000,...,25500,34200,43700,42000,27300,61600,36800,43200,30000,0

In [30]:
byCustomer = import_data.pivot_table(index="purchase_month", columns="顧客名", aggfunc="size", fill_value=0)
byCustomer

顧客名,さだ千佳子,中仁晶,中田美智子,丸山光臣,久保田倫子,亀井一徳,五十嵐春樹,井上桃子,井口寛治,井川真悠子,...,香椎優一,高原充則,高梨結衣,高沢美咲,高田さんま,鳥居広司,鶴岡薫,麻生莉緒,黄川田博之,黒谷長利
purchase_month,,,,,,,,,,,,,,,,,,,,,
201901,3,1,4,2,2,0,5,3,3,1,...,0,1,1,1,5,2,0,2,2,5
201902,9,1,2,2,1,4,2,1,0,4,...,4,0,3,2,0,1,2,4,0,1
201903,1,2,1,6,1,4,3,3,2,2,...,3,1,6,2,4,2,4,2,2,1
201904,0,3,1,2,0,2,2,0,3,2,...,2,4,2,3,4,3,2,1,2,0
201905,3,2,5,2,4,1,2,1,3,3,...,1,1,1,0,2,2,3,4,4,1
201906,1,3,0,4,1,1,1,2,2,3,...,7,3,0,2,1,0,2,1,2,4
201907,3,0,3,2,5,3,5,2,5,5,...,2,4,4,2,0,2,4,3,4,1

In [31]:
byRegion = import_data.pivot_table(index="purchase_month", columns="地域", aggfunc="size", fill_value=0)
byRegion

地域              A市  B市  C市  D市  E市  F市  G市  H市
purchase_month
201901          59  55  72  34  49  57  49  42
201902          71  46  65  48  61  52  43  63
201903          64  52  57  43  52  59  51  59
201904          64  48  54  45  48  58  40  52
201905          57  52  68  48  59  65  35  43
201906          53  47  61  30  51  51  58  58
201907          76  53  61  42  54  64  47  54

In [32]:
away_data = pd.merge(uriage_data, kokyaku_data, left_on="customer_name", right_on="顧客名", how="right")
away_data[away_data["purchase_date"].isnull()][["顧客名", "メールアドレス", "登録日"]]

       顧客名                  メールアドレス        登録日
2999  福井美希  fukui_miki1@example.com 2019-04-23